[env:mav_board]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_upload.flash_size = 8MB
board_build.partitions = partitions_custom.csv

build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MSC_ON_BOOT=0
  -D ARDUINO_USB_DFU_ON_BOOT=0


lib_deps =
  ElectronicCats/MPU6050
